# Location: ~/.config/wireplumber/wireplumber.conf.d/50-custom-audio-rules.conf

monitor.alsa.rules = [
  {
    # RULE 1: COMPLETELY DISABLE UNWANTED HARDWARE
    # Use this for internal motherboard audio or GPU HDMI ports you don't use.
    matches = [
    # Match by exact device name (best for PCI devices)
      {
        device.name = "alsa_card.pci-0000_09_00.4"
      },
      {
	    device.name = "alsa_card.pci-0000_07_00.1"
      }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  },
  
  {
    # RULE 2: HIDE DIGITAL OUTPUTS (ANALOG-ONLY MODE)
    # Use this for USB DACs/Speakers to remove the "Digital Stereo (IEC958)" clutter.
    # The '~' allows wildcard matching to ensure it works across different USB ports if you want to use device.name 
    matches = [
      {
        device.product.name = "FiiO K11 R2R"
      },
      {
	    device.product.name = "Buildwin Media-Player"
      }
    ]
    actions = {
      update-props = {
        # Forces WirePlumber to ignore digital profiles and only create Analog Sinks
        "device.profile-set" = "analog-only.conf"
      }
    }
  }
]
